In [1]:
import numpy as np

In [37]:
rand_arr = np.random.randint(1,100, [6, 4]) 
print(rand_arr)

[[67 39 89 13]
 [79 87 56 11]
 [67  7 42 93]
 [ 6 99 48 69]
 [44 58  3 77]
 [ 9 31 55 21]]


In [38]:
rand_arr[4]=rand_arr[0,:]+ rand_arr[2,:]
rand_arr[5]=rand_arr[1,:]+ rand_arr[3,:]

In [39]:
print(rand_arr)

[[ 67  39  89  13]
 [ 79  87  56  11]
 [ 67   7  42  93]
 [  6  99  48  69]
 [134  46 131 106]
 [ 85 186 104  80]]
