# I worked with Muhammad Asim 2211-016-KHI-DEG

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.metrics import f1_score, mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
from sklearn.neighbors import KNeighborsClassifier

In [3]:
wine = datasets.load_wine()
wine_x = wine.data
wine_y = wine.target

In [4]:
wine_x

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [5]:
wine_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [6]:
x_train, x_test, y_train, y_test = train_test_split(wine_x, wine_y, test_size=0.2)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [9]:
x_train[1]

array([-0.21377227,  2.20102755,  0.33852017,  0.54045974, -1.06750181,
       -0.93797676, -1.40163347,  0.83589485, -1.33602356,  1.09645451,
       -1.83108938, -1.06504572, -0.39959595])

In [15]:
data = np.array([[-0.21377227,2.20102755,0.33852017,0.54045974,-1.06750181,
       -0.93797676,-1.40163347,0.83589485,-1.33602356,1.09645451,
       -1.83108938,-1.06504572,-0.39959595]])

In [16]:
data.shape

(1, 13)

In [7]:
model = KNeighborsClassifier()

In [8]:
model.fit(x_train, y_train)

KNeighborsClassifier()

In [74]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 2, 0, 0,
       1, 2, 1, 0, 0, 0, 0, 1, 1, 1, 2, 1, 2, 2])

In [82]:
f1_score(y_test, y_pred, average="micro")

0.9444444444444444